sonar.projectKey=sonarqube-playwright-cicd
sonar.projectName=Sauce Playwright Vulnerability Suite
sonar.sources=tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts
sonar.exclusions=node_modules/**,playwright-report/**,test-results/**,**/*.json
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true